# Kitche+Vagrant doc: https://github.com/test-kitchen/kitchen-vagrant/blob/master/README.md
driver:
  name: vagrant
  #gui: true
  # Mount local /Users/amanly/chef-kits folder as /mnt/share on the VM
  synced_folders:
  - ["/Users/amanly/chef-kits", "/mnt/share", "disabled: false"]
  customize:
    cpus: 4
    memory: 4096

driver_config:
  # I don't login often, but when I do, I do it as root
  username: root
  password: vagrant

provisioner:
  name: chef_zero
  # Download and install this exact version of chef-client
  require_chef_omnibus: 12.3.0
  # Use the local chef-client rpm specified in install_chef_rpm.sh: 
  chef_omnibus_url: file:///mnt/share/install_chef_rpm.sh
  client_rb:
    # Use :enabled, :disabled or :audit_only to run the ServerSpec tests in the recipes 
    audit_mode: :enabled

platforms:
  - name: centos7
    driver:
      box: "opscode-centos-7.0"
      # see available box urls here: https://opscode-vm-bento.s3.amazonaws.com/
      # box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box
      box_url: file:///Users/amanly/chef-kits/opscode_centos-7.0_chef-provisionerless.box
      # Use the default host-only network along the NAT one. Makes life easier from a networking perspective
      network:
      - ["private_network", {ip: "192.168.56.55"}]

suites:
  - name: default
    run_list:
      - recipe[base-was::install-was]
      - recipe[base-was::manage-was-profile]
      - recipe[base-was::audit-was]
    attributes:
      base_was: 
        iim: 
          install_file_uri: file:///mnt/share/websphere/Install_Mgr_v1.6.2_Lnx_WASv8.5.5.zip
        was: 
          install_file_uris: 
            - "file:///mnt/share/websphere/WASND_v8.5.5_1of3.zip"
            - "file:///mnt/share/websphere/WASND_v8.5.5_2of3.zip"
            - "file:///mnt/share/websphere/WASND_v8.5.5_3of3.zip"
          jdbc: 
            oracle: 
              url: file:///mnt/share/oracle/ojdbc6.jar
